[server]
maxUploadSize = 500
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[runner]
fastReruns = true

[client]
showErrorDetails = false
toolbarMode = "minimal" # This hides the "Deploy" button and developer options
